export enum ERRORS {
  USER_NOT_AUTHENTICATED = "Err-001",
  USER_UNAUTHORIZED = "Err-002",
  OTP_EXPIRED = "Err-003",
  OTP_INVALID = "Err-004",
  PASSWORD_TOO_SHORT = "Err-005",
  PASSWORD_MISSING_CASE = "Err-006",
  PASSWORD_MISSING_SPECIAL_CHAR = "Err-007",
  INVALID_EMAIL = "Err-008",
  ACCOUNT_LOCK_WARNING = "Err-009",
  PASSWORD_MISMATCH = "Err-010",
  SESSION_EXPIRED = "Err-011",
  FAILED_OPERATION = "Err-012",
  FORBIDDEN_ACTION = "Err-013",
  INVALID_DATE_OR_TIME = "Err-014",
  INVALID_OID = "Err-015",
}

export enum INFO_MESSAGES {
  EMAIL_VERIFIED = "Msg-001",
  EMAIL_UNVERIFIED = "Msg-002",
  SUCCESSFUL_OPERATION = "Msg-003",
  UPDATED_SUCCESSFULLY = "Msg-004",
  OTP_SENT = "Msg-005",
}

export enum PermissionsEnum {
  SUPER_ADMIN = "perm-0000",
  CHANGE_PASSWORD = "perm-0001",
  ADD_USERS = "perm-0002",
  LIST_USERS = "perm-0003",
  DELETE_USER = "perm-0004",
  EDIT_SELF_PROFILE = "perm-0005",
  EDIT_USERS_PROFILE = "perm-0006",
  ADD_TICKET = "perm-0007",
  EDIT_TICKET = "perm-0008",
  DELETE_TICKET = "perm-0009",
  LIST_TICKET = "perm-0010",
  CHANGE_STATUS_TICKET = "perm-0011",
  CHANGE_PRIORITY_TICKET = "perm-0012",
  CHANGE_TICKET_VISIBILITY = "perm-0013",
}
